myObj = null
mydefine = function(h, F){
	myObj = F().$;
};
// minified.js config start -- use this comment to re-create a configuration in the Builder
// - Only sections add, always, each, error, get, ht, 
// - ie6compatibility, ie7compatibility, ie8compatibility, ie9compatibility, off, on, onclick, 
// - parsejson, promise, ready, remove, request, set, template, tojson, trigger, 
// - values, wait.


mydefine("minified",function(){function U(a){return a.substr(0,3)}function F(a){return a!=g?""+a:""}function A(a){return"string"==typeof a}function D(a){return a&&a.nodeType}function G(a){return a}function m(a,b,c){return F(a).replace(b,c!=g?c:"")}function H(a){return m(a,/^\s+|\s+$/g)}function B(a,b,c){for(var d in a)a.hasOwnProperty(d)&&b.call(c||a,d,a[d]);return a}function q(a,b,c){if(a)for(var d=0;d<a.length;d++)b.call(c||a,a[d],d);return a}function V(a,b){var c=[],d=n(b)?b:function(a){return b!=
a};q(a,function(b,f){d.call(a,b,f)&&c.push(b)});return c}function y(a,b,c){var d=[];a(b,function(a,f){r(a=c.call(b,a,f))?q(a,function(a){d.push(a)}):a!=g&&d.push(a)});return d}function C(a,b){var c=[];q(a,function(d,e){c.push(b.call(a,d,e))});return c}function J(a,b){var c=b||{},d;for(d in a)c[d]=a[d];return c}function W(a,b,c){return b==g?c:0>b?Math.max(a.length+b,0):Math.min(a.length,b)}function K(a,b,c){if(n(a))return a.apply(c&&b,C(c||b,G))}function X(a){C(a,function(a){return K(a,void 0,void 0)})}
function P(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}function Y(a){return m(a,/[\x00-\x1f'"\u2028\u2029]/g,P)}function I(a,b){for(var c=0,d,e=[];d=b.exec(a);)e.push(a.substring(c,d.index)),c=d.index+d[0].length;e.push(a.substr(c));return e}function Z(a,b){function c(a,c){var d=[];e.call(c||a,a,function(a,c){r(a)?q(a,function(a,b){c.call(a,a,b)}):B(a,function(a,b){c.call(b,a,b)})},b||G,function(){K(d.push,d,arguments)},ba);return d.join("")}if(L[a])return L[a];var d="with(_.isObject(obj)?obj:{}){"+
C(I(a,/{{|}}}?/g),function(a,c){var b,d=H(a),e=m(d,/^{/),d=d==e?"esc(":"";if(c%2)return(b=/^each\b(\s+([\w_]+(\s*,\s*[\w_]+)?)\s*:)?(.*)/.exec(e))?"each("+(H(b[4])?b[4]:"this")+", function("+b[2]+"){":(b=/^if\b(.*)/.exec(e))?"if("+b[1]+"){":(b=/^else\b\s*(if\b(.*))?/.exec(e))?"}else "+(b[1]?"if("+b[2]+")":"")+"{":(b=/^\/(if)?/.exec(e))?b[1]?"}\n":"});\n":(b=/^(var\s.*)/.exec(e))?b[1]+";":(b=/^#(.*)/.exec(e))?b[1]:(b=/(.*)::\s*(.*)/.exec(e))?"print("+d+'_.formatValue("'+Y(b[2])+'",'+(H(b[1])?b[1]:
"this")+(d&&")")+"));\n":"print("+d+(H(e)?e:"this")+(d&&")")+");\n";if(a)return'print("'+Y(a)+'");\n'}).join("")+"}",e=new Function("obj","each","esc","print","_",d);99<ca.push(c)&&delete L[ca.shift()];return L[a]=c}function ka(a){return m(a,/[<>'"&]/g,function(a){return"&#"+a.charCodeAt(0)+";"})}function da(a,b){return Z(a,ka)(b)}function n(a){return"function"==typeof a&&!a.item}function r(a){return a&&a.length!=g&&!A(a)&&!D(a)&&!n(a)&&a!==p}function ea(a,b){for(var c=0;a&&c<a.length;c++)a[c]===
b&&a.splice(c--,1)}function M(a){return a.Nia=a.Nia||++la}function fa(a,b){var c=[],d={},e;l(a,function(a){l(b(a),function(a){d[e=M(a)]||(c.push(a),d[e]=!0)})});return c}function ma(a,b,c,d,e,f){return function(h,k){var g,u=h||p.event,aa=!f,z=k||u.target||u.srcElement;if(f)for(;z&&z!=b&&!(aa=f(z));)z=z.parentNode;aa&&(g=(!a.apply(t(f?z:b),c||[u,d])||""==e)&&"|"!=e)&&!k&&(u.preventDefault&&(u.preventDefault(),u.stopPropagation()),u.cancelBubble=!0);return!g}}function Q(a,b){l(b,function(a){a.element.detachEvent("on"+
a.a,a.b)})}function ga(a){E?E.push(a):setTimeout(a,0)}function ha(a){return y(l,a,function(a){if(r(a))return ha(a);D(a)&&(a=a.cloneNode(!0),a.removeAttribute&&a.removeAttribute("id"));return a})}function t(a,b,c){return n(a)?ga(a):new N(v(a,b,c))}function v(a,b,c){function d(a){a=y(l,a,function z(a){return r(a)?y(l,a,z):a});return f?V(a,function(a){for(;a=a.parentNode;)if(a==f||c)return a==f}):a}function e(a,b){var c=RegExp("(^|\\s+)"+a+"(?=$|\\s)","i");return function(d){return a?c.test(d[b]):!0}}
var f,h,k,g;if(b&&1!=(b=v(b)).length)return fa(b,function(b){return v(a,b,c)});f=b&&b[0];if(!A(a))return d(a);if(f&&1!=D(f))return[];if(1<(b=a.split(/\s*,\s*/)).length)return fa(b,function(a){return v(a,f,c)});if(b=/(\S+)\s+(.+)$/.exec(a))return v(b[2],v(b[1],f),c);if(a!=(b=m(a,/^#/)))return d(document.getElementById(b));h=(b=/([\w-]*)\.?([\w-]*)/.exec(a))[1];g=b[2];b=(k=document.getElementsByClassName&&g)?(f||document).getElementsByClassName(g):(f||document).getElementsByTagName(h||"*");if(h=k?h:
g)b=V(b,e(h,k?"tagName":"className"));return c?d(b):b}function na(a,b){function c(a,b){var c=RegExp("(^|\\s+)"+a+"(?=$|\\s)","i");return function(d){return a?c.test(d[b]):!0}}var d={},e=d;if(n(a))return a;if("number"==typeof a)return function(b,c){return c==a};if(!a||"*"==a||A(a)&&(e=/^([\w-]*)\.?([\w-]*)$/.exec(a))){var f=c(e[1],"tagName"),h=c(e[2],"className");return function(a){return 1==D(a)&&f(a)&&h(a)}}if(b)return function(c){return t(a,b).find(c)!=g};t(a).each(function(a){d[M(a)]=!0});return function(a){return d[M(a)]}}
function l(a,b){r(a)?q(a,b):a!=g&&b(a,0);return a}function O(){function a(a,d){b==g&&a!=g&&(b=a,h=r(d)?d:[d],setTimeout(function(){q(c,function(a){a()})},0));return b}var b,c=[],d=arguments,e=d.length,f=0,h=[];q(d,function u(b,c){try{b.then?b.then(function(b){var d;(b&&"object"==typeof b||n(b))&&n(d=b.then)?u(d,c):(h[c]=C(arguments,G),++f==e&&a(!0,2>e?h[c]:h))},function(b){h[c]=C(arguments,G);a(!1,2>e?h[c]:[h[c][0],h,c])}):b(function(){a(!0,arguments)},function(){a(!1,arguments)})}catch(d){a(!1,[d,
h,c])}});a.stop=function(){q(d,function(a){a.stop&&a.stop()});return K(a.stop0)};var k=a.then=function(d,e){function f(){try{var a=b?d:e;n(a)?function oa(a){try{var b,c=0;if((a&&"object"==typeof a||n(a))&&n(b=a.then)){if(a===k)throw new TypeError;b.call(a,function(a){c++||oa(a)},function(a){c++||k(!1,[a])});k.stop0=a.stop}else k(!0,[a])}catch(d){c++||k(!1,[d])}}(K(a,ia,h)):k(b,h)}catch(c){k(!1,[c])}}var k=O();k.stop0=a.stop;b!=g?setTimeout(f,0):c.push(f);return k};a.always=function(a){return k(a,
a)};a.error=function(a){return k(0,a)};return a}function N(a,b){var c=0;if(a)for(var d=0,e=a.length;d<e;d++){var f=a[d];if(b&&r(f))for(var h=0,k=f.length;h<k;h++)this[c++]=f[h];else this[c++]=f}else this[c++]=b;this.length=c;this._=!0}function ba(){return new N(arguments,!0)}var p=this,R={},S={},la=1,w={},E=/^[ic]/.test(document.readyState)?g:[],x=!!document.all&&!document.addEventListener,g=null,ia,T=I("January,February,March,April,May,June,July,August,September,October,November,December",/,/g);
C(T,U);T=I("Sunday,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday",/,/g);C(T,U);I("am,pm",/,/g);I("am,am,am,am,am,am,am,am,am,am,am,am,pm,pm,pm,pm,pm,pm,pm,pm,pm,pm,pm,pm",/,/g);var L={},ca=[];J({each:function(a){return function(b,c,d){return a(this,b,c,d)}}(q),e:0,remove:function(){l(this,function(a){x&&1==D(a)&&(l(v("*",a),function(a){Q(0,w[a.Nia]);delete w[a.Nia]}),Q(0,w[a.Nia]),delete w[a.Nia]);a.parentNode.removeChild(a)})},get:function(a,b){var c=this,d=c[0];if(d){if(A(a)){var e=/^(\W*)(.*)/.exec(m(a,
/^%/,"@data-")),f=e[1],d=S[f]?S[f](this,e[2]):"$"==a?c.get("className"):"$$"==a?x?d.style.cssText:c.get("@style"):"$$slide"==a?c.get("$height"):"$$fade"==a||"$$show"==a?"hidden"==c.get("$visibility")||"none"==c.get("$display")?0:"$$fade"==a?x?isNaN(c.get("$filter",!0))?1:c.get("$filter",!0)/100:isNaN(c.get("$opacity",!0))?1:c.get("$opacity",!0):1:"$$scrollX"==a?p.pageXOffset!=g?p.pageXOffset:(document.documentElement||document.body.parentNode||document.body).scrollLeft:"$$scrollY"==a?p.pageXOffset!=
g?p.pageYOffset:(document.documentElement||document.body.parentNode||document.body).scrollTop:"$"==f?p.getComputedStyle?p.getComputedStyle(d,g).getPropertyValue(m(e[2],/[A-Z]/g,function(a){return"-"+a.toLowerCase()})):(d.currentStyle||d.style)[m(e[2],/^float$/,"cssFloat")]:"@"==f?d.getAttribute(e[2]):d[e[2]];return b?parseFloat(m(d,/^[^\d-]+/)):d}var h={};(r(a)?l:B)(a,function(a){h[a]=c.get(a,b)});return h}},set:function(a,b){var c=this;if(b!==ia){var d=/^(\W*)(.*)/.exec(m(m(a,/^\$float$/,"cssFloat"),
/^%/,"@data-")),e=d[1];if(R[e])R[e](this,d[2],b);else"$$fade"==a?c.set({$visibility:b?"visible":"hidden"}).set(x?1>b?{$filter:"alpha(opacity = "+100*b+")",$zoom:1}:{$filter:""}:{$opacity:b}):"$$slide"==a?c.set({$visibility:b?"visible":"hidden",$overflow:"hidden",$height:/px/.test(b)?b:function(a,c,d){a=t(d);d={$position:"absolute",$visibility:"hidden",$display:"block",$height:g};c=a.get(d);d=a.set(d).get("clientHeight");a.set(c);return d*b+"px"}}):"$$show"==a?b?c.set({$visibility:b?"visible":"hidden",
$display:""}).set({$display:function(a){return"none"==a?"block":a}}):c.set({$display:"none"}):"$$"==a?x?c.set("$cssText",b):c.set("@style",b):l(this,function(c,h){var k=n(b)?b(t(c).get(a),h,c):b;"$"==e?d[2]?c.style[d[2]]=k:l(k&&k.split(/\s+/),function(a){var b=m(a,/^[+-]/),d=c.className||"",e=m(d,RegExp("(^|\\s+)"+b+"(?=$|\\s)"));if(/^\+/.test(a)||b==a&&d==e)e+=" "+b;c.className=H(e)}):"$$scrollX"==a?c.scroll(k,t(c).get("$$scrollY")):"$$scrollY"==a?c.scroll(t(c).get("$$scrollX"),k):"@"==e?k==g?c.removeAttribute(d[2]):
c.setAttribute(d[2],k):c[d[2]]=k})}else A(a)||n(a)?c.set("$",a):B(a,function(a,b){c.set(a,b)});return c},add:function(a,b){return this.each(function(c,d){function e(a){r(a)?l(a,e):n(a)?e(a(c,d)):a!=g&&(a=D(a)?a:document.createTextNode(a),f?f.parentNode.insertBefore(a,f.nextSibling):b?b(a,c,c.parentNode):c.appendChild(a),f=a)}var f;e(d&&!n(a)?ha(a):a)})},values:function(a){var b=a||{};this.each(function(a){var d=a.name||a.id,e=F(a.value);if(/form/i.test(a.tagName))for(d=0;d<a.elements.length;d++)t(a.elements[d]).values(b);
else!d||/ox|io/i.test(a.type)&&!a.checked||(b[d]=b[d]==g?e:y(l,[b[d],e],G))});return b},on:function(a,b,c,d,e){return n(b)?this.on(g,a,b,c,e):A(d)?this.on(a,b,c,g,d):this.each(function(f,h){l(a?v(a,f):f,function(a){l(F(b).split(/\s/),function(b){var f=m(b,/[?|]/),g=!!e&&("blur"==f||"focus"==f),l=ma(c,a,d,h,m(b,/[^?|]/g),e&&na(e,a));b={element:a,b:l,a:f,c:g};(c.M=c.M||[]).push(b);x?(a.attachEvent("on"+b.a+(g?"in":""),l),f=M(a),(w[f]=w[f]||[]).push(b)):(a.addEventListener(f,l,g),(a.M=a.M||[]).push(b))})})})},
onClick:function(a,b,c,d){return n(b)?this.on(a,"click",b,c,d):this.onClick(g,a,b,c)},trigger:function(a,b){return this.each(function(c){for(var d,e=c;e&&!d;)l(x?w[e.Nia]:e.M,function(e){e.a==a&&(d=d||!e.b(b,c))}),e=e.parentNode})},ht:function(a,b){var c;if(2<arguments.length){c=arguments;var d=[];if(c)for(var e=W(c,void 0,c.length),f=W(c,1,0);f<e;f++)d.push(c[f]);c=d;d=void 0;for(e=0;e<c.length;e++)d=J(c[e],d);c=d}else c=b;return this.set("innerHTML",n(a)?a(c):/{{/.test(a)?da(a,c):/^#\S+$/.test(a)?
da(v(a,void 0,void 0)[0].text,c):a)}},N.prototype);J({request:function(a,b,c,d){d=d||{};var e,f=0,h=O(),k=c&&c.constructor==d.constructor;try{h.xhr=e=p.XMLHttpRequest?new XMLHttpRequest:new ActiveXObject("Msxml2.XMLHTTP.3.0"),h.stop0=function(){e.abort()},k&&(c=y(B,c,function(a,b){return y(l,b,function(b){return encodeURIComponent(a)+(b!=g?"="+encodeURIComponent(b):"")})}).join("&")),c==g||/post/i.test(a)||(b+="?"+c,c=g),e.open(a,b,!0,d.user,d.pass),k&&/post/i.test(a)&&e.setRequestHeader("Content-Type",
"application/x-www-form-urlencoded"),B(d.headers,function(a,b){e.setRequestHeader(a,b)}),B(d.xhr,function(a,b){e[a]=b}),e.onreadystatechange=function(){4!=e.readyState||f++||(200==e.status?h(!0,[e.responseText,e]):h(!1,[e.status,e.responseText,e]))},e.send(c)}catch(m){f||h(!1,[0,g,F(m)])}return h},toJSON:function b(c){return c==g?""+c:A(c=c.valueOf())?'"'+m(c,/[\\\"\x00-\x1f\u2028\u2029]/g,P)+'"':r(c)?"["+y(l,c,b).join()+"]":c&&"object"==typeof c?"{"+y(B,c,function(c,e){return b(c)+":"+b(e)}).join()+
"}":F(c)},parseJSON:p.JSON?p.JSON.parse:function(b){b=m(b,/[\x00\xad\u0600-\uffff]/g,P);if(/^[[\],:{}\s]*$/.test(m(m(b,/\\["\\\/bfnrtu]/g),/"[^"\\\n\r]*"|true|false|null|[\d.eE+-]+/g)))return eval("("+b+")")},ready:ga,off:function(b){l(b.M,function(b){x?(b.element.detachEvent("on"+b.a+(b.c?"in":""),b.b),ea(w[b.element.Nia],b)):(b.element.removeEventListener(b.a,b.b,b.c),ea(b.element.M,b))});b.M=g},wait:function(b,c){var d=O(),e=setTimeout(function(){d(!0,c)},b);d.stop0=function(){d(!1);clearTimeout(e)};
return d}},t);J({each:q,toObject:function(b,c){var d={};q(b,function(b){d[b]=c});return d},template:Z,d:0,promise:O},ba);if(x){var ja=function(){X(E);E=g};document.attachEvent("onreadystatechange",function(){/^[ic]/.test(document.readyState)&&ja()});p.attachEvent("onload",ja)}else document.addEventListener("DOMContentLoaded",function(){X(E);E=g},!1);p.f=function(){l(w,Q)};return{$:t,M:N,getter:S,setter:R}});
module.exports = myObj;