myObj = null
mydefine = function(h, F){
	myObj = F().$;
};
// minified.js config start -- use this comment to re-create a configuration in the Builder
// - Only sections always, each, error, fill, get, ie6compatibility, 
// - ie7compatibility, ie8compatibility, ie9compatibility, off, on, onclick, parsejson, 
// - promise, ready, request, set, tojson, trigger, values, wait.


mydefine("minified",function(){function E(a){return a!=g?""+a:""}function A(a){return"string"==typeof a}function B(a){return a&&a.nodeType}function F(a){return a}function m(a,b,c){return E(a).replace(b,c!=g?c:"")}function C(a,b,c){for(var d in a)a.hasOwnProperty(d)&&b.call(c||a,d,a[d]);return a}function r(a,b,c){if(a)for(var d=0;d<a.length;d++)b.call(c||a,a[d],d);return a}function P(a,b){var c=[],d=n(b)?b:function(a){return b!=a};r(a,function(b,f){d.call(a,b,f)&&c.push(b)});return c}function x(a,b,
c){var d=[];a(b,function(a,f){t(a=c.call(b,a,f))?r(a,function(a){d.push(a)}):a!=g&&d.push(a)});return d}function G(a,b){var c=[];r(a,function(d,e){c.push(b.call(a,d,e))});return c}function K(a,b){var c=b||{},d;for(d in a)c[d]=a[d]}function L(a,b,c){if(n(a))return a.apply(c&&b,G(c||b,F))}function Q(a){G(a,function(a){return L(a,void 0,void 0)})}function R(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}function n(a){return"function"==typeof a&&!a.item}function t(a){return a&&a.length!=
g&&!A(a)&&!B(a)&&!n(a)&&a!==p}function S(a,b){for(var c=0;a&&c<a.length;c++)a[c]===b&&a.splice(c--,1)}function H(a){return a.Nia=a.Nia||++Z}function T(a,b){var c=[],d={},e;l(a,function(a){l(b(a),function(a){d[e=H(a)]||(c.push(a),d[e]=!0)})});return c}function aa(a,b,c,d,e,f){return function(h,k){var g,u=h||p.event,U=!f,y=k||u.target||u.srcElement;if(f)for(;y&&y!=b&&!(U=f(y));)y=y.parentNode;U&&(g=(!a.apply(q(f?y:b),c||[u,d])||""==e)&&"|"!=e)&&!k&&(u.preventDefault&&(u.preventDefault(),u.stopPropagation()),
u.cancelBubble=!0);return!g}}function M(a,b){l(b,function(a){a.element.detachEvent("on"+a.a,a.b)})}function V(a){D?D.push(a):setTimeout(a,0)}function W(a){return x(l,a,function(a){if(t(a))return W(a);B(a)&&(a=a.cloneNode(!0),a.removeAttribute&&a.removeAttribute("id"));return a})}function q(a,b,c){return n(a)?V(a):new I(z(a,b,c))}function z(a,b,c){function d(a){a=x(l,a,function y(a){return t(a)?x(l,a,y):a});return f?P(a,function(a){for(;a=a.parentNode;)if(a==f||c)return a==f}):a}function e(a,b){var c=
RegExp("(^|\\s+)"+a+"(?=$|\\s)","i");return function(d){return a?c.test(d[b]):!0}}var f,h,k,g;if(b&&1!=(b=z(b)).length)return T(b,function(b){return z(a,b,c)});f=b&&b[0];if(!A(a))return d(a);if(f&&1!=B(f))return[];if(1<(b=a.split(/\s*,\s*/)).length)return T(b,function(a){return z(a,f,c)});if(b=/(\S+)\s+(.+)$/.exec(a))return z(b[2],z(b[1],f),c);if(a!=(b=m(a,/^#/)))return d(document.getElementById(b));h=(b=/([\w-]*)\.?([\w-]*)/.exec(a))[1];g=b[2];b=(k=document.getElementsByClassName&&g)?(f||document).getElementsByClassName(g):
(f||document).getElementsByTagName(h||"*");if(h=k?h:g)b=P(b,e(h,k?"tagName":"className"));return c?d(b):b}function ba(a,b){function c(a,b){var c=RegExp("(^|\\s+)"+a+"(?=$|\\s)","i");return function(d){return a?c.test(d[b]):!0}}var d={},e=d;if(n(a))return a;if("number"==typeof a)return function(b,c){return c==a};if(!a||"*"==a||A(a)&&(e=/^([\w-]*)\.?([\w-]*)$/.exec(a))){var f=c(e[1],"tagName"),h=c(e[2],"className");return function(a){return 1==B(a)&&f(a)&&h(a)}}if(b)return function(c){return q(a,b).find(c)!=
g};q(a).each(function(a){d[H(a)]=!0});return function(a){return d[H(a)]}}function l(a,b){t(a)?r(a,b):a!=g&&b(a,0);return a}function J(){function a(a,d){b==g&&a!=g&&(b=a,h=t(d)?d:[d],setTimeout(function(){r(c,function(a){a()})},0));return b}var b,c=[],d=arguments,e=d.length,f=0,h=[];r(d,function u(b,c){try{b.then?b.then(function(b){var d;(b&&"object"==typeof b||n(b))&&n(d=b.then)?u(d,c):(h[c]=G(arguments,F),++f==e&&a(!0,2>e?h[c]:h))},function(b){h[c]=G(arguments,F);a(!1,2>e?h[c]:[h[c][0],h,c])}):b(function(){a(!0,
arguments)},function(){a(!1,arguments)})}catch(d){a(!1,[d,h,c])}});a.stop=function(){r(d,function(a){a.stop&&a.stop()});return L(a.stop0)};var k=a.then=function(d,e){function f(){try{var a=b?d:e;n(a)?function ca(a){try{var b,c=0;if((a&&"object"==typeof a||n(a))&&n(b=a.then)){if(a===k)throw new TypeError;b.call(a,function(a){c++||ca(a)},function(a){c++||k(!1,[a])});k.stop0=a.stop}else k(!0,[a])}catch(d){c++||k(!1,[d])}}(L(a,X,h)):k(b,h)}catch(c){k(!1,[c])}}var k=J();k.stop0=a.stop;b!=g?setTimeout(f,
0):c.push(f);return k};a.always=function(a){return k(a,a)};a.error=function(a){return k(0,a)};return a}function I(a,b){var c=0;if(a)for(var d=0,e=a.length;d<e;d++){var f=a[d];if(b&&t(f))for(var h=0,k=f.length;h<k;h++)this[c++]=f[h];else this[c++]=f}else this[c++]=b;this.length=c;this._=!0}var p=this,N={},O={},Z=1,v={},D=/^[ic]/.test(document.readyState)?g:[],w=!!document.all&&!document.addEventListener,g=null,X;K({each:function(a){return function(b,c,d){return a(this,b,c,d)}}(r),f:0,remove:function(){l(this,
function(a){w&&1==B(a)&&(l(z("*",a),function(a){M(0,v[a.Nia]);delete v[a.Nia]}),M(0,v[a.Nia]),delete v[a.Nia]);a.parentNode.removeChild(a)})},get:function(a,b){var c=this,d=c[0];if(d){if(A(a)){var e=/^(\W*)(.*)/.exec(m(a,/^%/,"@data-")),f=e[1],d=O[f]?O[f](this,e[2]):"$"==a?c.get("className"):"$$"==a?w?d.style.cssText:c.get("@style"):"$$slide"==a?c.get("$height"):"$$fade"==a||"$$show"==a?"hidden"==c.get("$visibility")||"none"==c.get("$display")?0:"$$fade"==a?w?isNaN(c.get("$filter",!0))?1:c.get("$filter",
!0)/100:isNaN(c.get("$opacity",!0))?1:c.get("$opacity",!0):1:"$$scrollX"==a?p.pageXOffset!=g?p.pageXOffset:(document.documentElement||document.body.parentNode||document.body).scrollLeft:"$$scrollY"==a?p.pageXOffset!=g?p.pageYOffset:(document.documentElement||document.body.parentNode||document.body).scrollTop:"$"==f?p.getComputedStyle?p.getComputedStyle(d,g).getPropertyValue(m(e[2],/[A-Z]/g,function(a){return"-"+a.toLowerCase()})):(d.currentStyle||d.style)[m(e[2],/^float$/,"cssFloat")]:"@"==f?d.getAttribute(e[2]):
d[e[2]];return b?parseFloat(m(d,/^[^\d-]+/)):d}var h={};(t(a)?l:C)(a,function(a){h[a]=c.get(a,b)});return h}},set:function(a,b){var c=this;if(b!==X){var d=/^(\W*)(.*)/.exec(m(m(a,/^\$float$/,"cssFloat"),/^%/,"@data-")),e=d[1];if(N[e])N[e](this,d[2],b);else"$$fade"==a?c.set({$visibility:b?"visible":"hidden"}).set(w?1>b?{$filter:"alpha(opacity = "+100*b+")",$zoom:1}:{$filter:""}:{$opacity:b}):"$$slide"==a?c.set({$visibility:b?"visible":"hidden",$overflow:"hidden",$height:/px/.test(b)?b:function(a,c,
d){a=q(d);d={$position:"absolute",$visibility:"hidden",$display:"block",$height:g};c=a.get(d);d=a.set(d).get("clientHeight");a.set(c);return d*b+"px"}}):"$$show"==a?b?c.set({$visibility:b?"visible":"hidden",$display:""}).set({$display:function(a){return"none"==a?"block":a}}):c.set({$display:"none"}):"$$"==a?w?c.set("$cssText",b):c.set("@style",b):l(this,function(c,h){var k=n(b)?b(q(c).get(a),h,c):b;"$"==e?d[2]?c.style[d[2]]=k:l(k&&k.split(/\s+/),function(a){var b=m(a,/^[+-]/),d=c.className||"",e=
m(d,RegExp("(^|\\s+)"+b+"(?=$|\\s)"));if(/^\+/.test(a)||b==a&&d==e)e+=" "+b;c.className=m(e,/^\s+|\s+$/g)}):"$$scrollX"==a?c.scroll(k,q(c).get("$$scrollY")):"$$scrollY"==a?c.scroll(q(c).get("$$scrollX"),k):"@"==e?k==g?c.removeAttribute(d[2]):c.setAttribute(d[2],k):c[d[2]]=k})}else A(a)||n(a)?c.set("$",a):C(a,function(a,b){c.set(a,b)});return c},add:function(a,b){return this.each(function(c,d){function e(a){t(a)?l(a,e):n(a)?e(a(c,d)):a!=g&&(a=B(a)?a:document.createTextNode(a),f?f.parentNode.insertBefore(a,
f.nextSibling):b?b(a,c,c.parentNode):c.appendChild(a),f=a)}var f;e(d&&!n(a)?W(a):a)})},fill:function(a){return this.each(function(a){q(a.childNodes).remove()}).add(a)},values:function(a){var b=a||{};this.each(function(a){var d=a.name||a.id,e=E(a.value);if(/form/i.test(a.tagName))for(d=0;d<a.elements.length;d++)q(a.elements[d]).values(b);else!d||/ox|io/i.test(a.type)&&!a.checked||(b[d]=b[d]==g?e:x(l,[b[d],e],F))});return b},on:function(a,b,c,d,e){return n(b)?this.on(g,a,b,c,e):A(d)?this.on(a,b,c,g,
d):this.each(function(f,h){l(a?z(a,f):f,function(a){l(E(b).split(/\s/),function(b){var f=m(b,/[?|]/),g=!!e&&("blur"==f||"focus"==f),l=aa(c,a,d,h,m(b,/[^?|]/g),e&&ba(e,a));b={element:a,b:l,a:f,c:g};(c.M=c.M||[]).push(b);w?(a.attachEvent("on"+b.a+(g?"in":""),l),f=H(a),(v[f]=v[f]||[]).push(b)):(a.addEventListener(f,l,g),(a.M=a.M||[]).push(b))})})})},onClick:function(a,b,c,d){return n(b)?this.on(a,"click",b,c,d):this.onClick(g,a,b,c)},trigger:function(a,b){return this.each(function(c){for(var d,e=c;e&&
!d;)l(w?v[e.Nia]:e.M,function(e){e.a==a&&(d=d||!e.b(b,c))}),e=e.parentNode})},e:0},I.prototype);K({request:function(a,b,c,d){d=d||{};var e,f=0,h=J(),k=c&&c.constructor==d.constructor;try{h.xhr=e=p.XMLHttpRequest?new XMLHttpRequest:new ActiveXObject("Msxml2.XMLHTTP.3.0"),h.stop0=function(){e.abort()},k&&(c=x(C,c,function(a,b){return x(l,b,function(b){return encodeURIComponent(a)+(b!=g?"="+encodeURIComponent(b):"")})}).join("&")),c==g||/post/i.test(a)||(b+="?"+c,c=g),e.open(a,b,!0,d.user,d.pass),k&&
/post/i.test(a)&&e.setRequestHeader("Content-Type","application/x-www-form-urlencoded"),C(d.headers,function(a,b){e.setRequestHeader(a,b)}),C(d.xhr,function(a,b){e[a]=b}),e.onreadystatechange=function(){4!=e.readyState||f++||(200==e.status?h(!0,[e.responseText,e]):h(!1,[e.status,e.responseText,e]))},e.send(c)}catch(m){f||h(!1,[0,g,E(m)])}return h},toJSON:function b(c){return c==g?""+c:A(c=c.valueOf())?'"'+m(c,/[\\\"\x00-\x1f\u2028\u2029]/g,R)+'"':t(c)?"["+x(l,c,b).join()+"]":c&&"object"==typeof c?
"{"+x(C,c,function(c,e){return b(c)+":"+b(e)}).join()+"}":E(c)},parseJSON:p.JSON?p.JSON.parse:function(b){b=m(b,/[\x00\xad\u0600-\uffff]/g,R);if(/^[[\],:{}\s]*$/.test(m(m(b,/\\["\\\/bfnrtu]/g),/"[^"\\\n\r]*"|true|false|null|[\d.eE+-]+/g)))return eval("("+b+")")},ready:V,off:function(b){l(b.M,function(b){w?(b.element.detachEvent("on"+b.a+(b.c?"in":""),b.b),S(v[b.element.Nia],b)):(b.element.removeEventListener(b.a,b.b,b.c),S(b.element.M,b))});b.M=g},wait:function(b,c){var d=J(),e=setTimeout(function(){d(!0,
c)},b);d.stop0=function(){d(!1);clearTimeout(e)};return d}},q);K({each:r,toObject:function(b,c){var d={};r(b,function(b){d[b]=c});return d},d:0,promise:J},function(){return new I(arguments,!0)});if(w){var Y=function(){Q(D);D=g};document.attachEvent("onreadystatechange",function(){/^[ic]/.test(document.readyState)&&Y()});p.attachEvent("onload",Y)}else document.addEventListener("DOMContentLoaded",function(){Q(D);D=g},!1);p.g=function(){l(v,M)};return{$:q,M:I,getter:O,setter:N}});

module.exports = myObj;